//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseExecution
    {
        public int TestCaseId { get; set; }
        public int WebElementId { get; set; }
        public int TestCaseStepSequence { get; set; }
        public string StepDescription { get; set; }
        public int id { get; set; }
    
        public virtual TestCase TestCase { get; set; }
        public virtual WebElement WebElement { get; set; }
    }
}
