//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebElement()
        {
            this.TestCaseExecutions = new HashSet<TestCaseExecution>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> IsMultipleElemets { get; set; }
        public string ElementName { get; set; }
        public string Locator { get; set; }
        public string FindElementMachanism { get; set; }
        public string InputType { get; set; }
        public string InputData { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestCaseExecution> TestCaseExecutions { get; set; }
    }
}
